//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jeylabsCodeReviews {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jeylabsCodeReviews.MainWindowResources", typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Circle Drawing has been chosen now painting to screen..
        /// </summary>
        internal static string Circle_DebugText {
            get {
                return ResourceManager.GetString("Circle_DebugText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside Constructor for ShapePageViewModel..
        /// </summary>
        internal static string MainPageViewModel_ConstructorDebug {
            get {
                return ResourceManager.GetString("MainPageViewModel_ConstructorDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside the TextInputViewModel: ShapeDescription method, ready for processing
        ///Then Pass processed array of strings to theShapeDrawerViewModel to process and build shape object. oh btw string sent was {0}.
        /// </summary>
        internal static string TextInputViewModel_ShapeDescription_ {
            get {
                return ResourceManager.GetString("TextInputViewModel_ShapeDescription_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside the TextInputViewModel: ShapeDescription method,.
        /// </summary>
        internal static string TextInputViewModel_ShapeDescription_Inside_the_TextInputViewModel__ShapeDescription_method_ {
            get {
                return ResourceManager.GetString("TextInputViewModel_ShapeDescription_Inside_the_TextInputViewModel__ShapeDescripti" +
                        "on_method_", resourceCulture);
            }
        }
    }
}
